### ISSUE TITLE
Installation instructions have errors

### ISSUE THREAD

**Issue by raziurtotha** [bilel-bj/ROSGPT_Vision#1]
How to clone these repo as the same directory name? I don't really understand. Is that a mistake?

  git clone https://github.com/Vision-CAIR/MiniGPT-4.git rosgpt_vision
  git clone https://github.com/haotian-liu/LLaVA.git rosgpt_vision

**Comment by winster-bai** [comment]
I have the same question 😔

**Comment by Purulence666** [comment]
> I have the same question LOL.

🤣

**Comment by AnasHXH** [comment]
Hi @Purulence666 and @winster-bai

Clone the First Repository: You can start by cloning the first repository into the rosgpt_vision directory as you have done. This will create a new directory named rosgpt_vision and clone the repository into it.


`git clone https://github.com/bilel-bj/ROSGPT_Vision.git rosgpt_vision`

Navigate to the Directory: Once the first repository is cloned, you should navigate into the rosgpt_vision directory.

`cd rosgpt_vision`
Clone Additional Repositories Inside: Now that you are inside the rosgpt_vision directory, you can clone the additional repositories. However, since you want them in the same directory, you'll need to use a different approach, such as using git submodule.

`git submodule add https://github.com/Vision-CAIR/MiniGPT-4.git`

`git submodule add https://github.com/haotian-liu/LLaVA.git`

This will add these repositories as submodules within your rosgpt_vision directory. Each repository will be in its own subdirectory within rosgpt_vision.

**Comment by raziurtotha** [comment]
Hi @AnasHXH , sorry for the confusion. I don't want to install the additional repositories under rosgpt_vision. I meant to ask, by following your instructions, I tried to run the installation process. But it resulted into error that 
"destination path 'rosgpt_vision' already exists and is not an empty directory". So I was wondering how the following two lines from the installation instructions, 
git clone https://github.com/Vision-CAIR/MiniGPT-4.git rosgpt_vision
git clone https://github.com/haotian-liu/LLaVA.git rosgpt_vision"

should be used.

**Comment by AnasHXH** [comment]
Thank you for your Comment @Purulence666, commands have been modified

  `git clone https://github.com/bilel-bj/ROSGPT_Vision.git`
  `cd ROSGPT_Vision`
  `git clone https://github.com/Vision-CAIR/MiniGPT-4.git`
  `git clone https://github.com/haotian-liu/LLaVA.git`
  `conda env create -f environment.yml`
  `conda activate ROSGPT_Vision`
